### ISSUE TITLE
When will the code release?

### ISSUE THREAD

**Issue by Ego-J** [shanshuo/Social-Fabric#1]
Hi,

It's an amazing work :)

When will you release your code ? Are the features you used in experiments will be included as well?

Thank you.

**Comment by shanshuo** [comment]
Thanks for your interest in our work. I'm doing an internship now so the released date is postponed. And we plan to update the code after the ICCV conference. If we have enough cloud space, the features will be included.

**Comment by Ego-J** [comment]
@shanshuo Thanks for your reply!
